### ISSUE TITLE
Encounter setup issue here

### ISSUE THREAD

**Issue by Winniepoom** [presentator/presentator#185] opened 2022-06-14 05:07 UTC
i'm a bit newbie in Linux here when i try to install development environment with Docker i had a problem here any advice ?
![pe](https://user-images.githubusercontent.com/107398226/173497555-03a4d1a0-30b5-4e45-8a3e-348a2b9c350b.png)
![pe1](https://user-images.githubusercontent.com/107398226/173497560-b6d1a83c-5a4e-48c6-ac11-f02ea02682e4.png)

**Comment by ganigeorgiev** [comment] 2022-06-14 06:15
As far as I can see from the screenshots, there seems to be permission errors during the development docker setup script execution. It's hard to tell what exactly is the reason for the failures.

Could you provide a little more information about your local setup (which docker and docker-compose version you are using, linux os, etc.)?

_p.s. If you are trying to install Presentator on production env, I recommend to follow the [starter package](https://github.com/presentator/presentator/tree/master/packages/starter) instructions and/or its [dockerized version](https://github.com/presentator/presentator-docker)._

**Comment by Winniepoom** [comment] 2022-06-14 08:23
i try dockerized version as your recommend. installation seem to be fine but i can't access web gui.
i used CT (Ubuntu 21.04) on proxmox 
docker version 20.10.14 
docker compose version 2.3.3

and this is my vhost config
<VirtualHost *:80>
    ServerAdmin webmaster@localhost   
    ServerName localhost
    DocumentRoot /var/www/html/web
    ErrorLog ${APACHE_LOG_DIR}/api.error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    <Directory /var/www/html/web>
        Options All FollowSymlinks MultiViews
        AllowOverride All
    </Directory>
</VirtualHost>

ps. sorry for bad eng

**Comment by ganigeorgiev** [comment] 2022-06-14 08:52
Hi again.

I've tried with similar docker and docker-compose versions as yours and couldn't reproduce the above errors.

Unfortunately, I'm not familiar with proxmox and how it works but I could help you debug it.

Do you use docker-compose? If Yes then what is the content of your docker-compose.yml file (you could check if the vhost volume path is correctly defined and mounted)?

Are there any reported errors or logs? If you are following the [docker-compose example](https://github.com/presentator/presentator-docker/tree/master/docker-compose-example) you could also try running the app in non-background mode, aka. without `-d` flag: just `docker-compose up`)?

**Comment by Winniepoom** [comment] 2022-06-14 09:08
here my docker-compose.yml
version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mariadb:
    image: mariadb:10
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=presentator
      - MYSQL_USER=presentator
      - MYSQL_PASSWORD=presentator

  presentator:
    image: ganigeorgiev/presentator:latest
    depends_on:
      - mariadb
    restart: always
    environment:
      - VIRTUAL_HOST=example.com
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./vhosts.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./base-local.php:/var/www/html/config/base-local.php
      - ./params-local.php:/var/www/html/config/params-local.php
      - ./spa.json:/var/www/html/config/spa.json
      - ./storage:/var/www/html/web/storage
      

      i check in /etc but there are no apache2 folder

**Comment by ganigeorgiev** [comment] 2022-06-14 09:16
How do you access the vhost - using an the vm IP?
Your vhost serverName usually should match with what you have in the docker-compose VIRTUAL_HOST environment (you are using example.com).

---

Additionally, to make sure that proxmox is not the culprit, you could also install docker and docker-compose on your local Windows machine and try to download and follow the [docker-compose example instructions](https://github.com/presentator/presentator-docker/tree/master/docker-compose-example). Note that you also may need to register the vhost address in your local hosts file (for linux is `/etc/hosts` for windows usually it is something like `C:\Windows\System32\drivers\etc\hosts`).

**Comment by Winniepoom** [comment] 2022-06-16 08:43
now i manage to install presentator it already with docker method thank you for your advice 
but now i just want to add login with google method in my sign in page how do i enable auth panel like in your website or i have to create by myself ? 
![asdzz](https://user-images.githubusercontent.com/107398226/174030138-534a5d3b-91ef-48c5-8681-e7ec592f2f96.PNG)

**Comment by Winniepoom** [comment] 2022-06-16 09:51
there is another way to change URL from local host like this http://192.168.1.54/#/sign-up  => http://thisismypresentator/#/sign-up
because i had encounter issue with Google OAuth
![aszzz](https://user-images.githubusercontent.com/107398226/174044400-17738da9-f0c0-4625-82e0-58c3b8d83de8.PNG)

**Comment by ganigeorgiev** [comment] 2022-06-16 10:22
You could use `localhost` as base domain if you want to target localhost, eg. something like `localhost/#/auth-callback` (note that the path is /auth-callback, not /sign-up; it should match with what you have in params-local.php for authClientRedirectUri).

**Comment by ganigeorgiev** [comment] 2022-06-18 10:01
In any case, once you have obtained a google client id and secret and [register the google oauth2 client in your base-local.php](https://github.com/presentator/presentator-starter#allow-3rd-party-authentication-oauth2), the "Sign in with Google" option will show up in the UI.
I'm closing the issue for now. If you still have any troubles making it work, feel free to comment and I'll reopen it.

**Closed by ganigeorgiev** 2022-06-18 10:01 UTC
Labels: support
