### ISSUE TITLE
fix side of screen

### ISSUE THREAD

**Issue by mvwijland** [presentator/presentator#171] opened 2021-02-04 12:46 UTC
It would be great if you could fix the left or right side of the screen. So that a 'menu' on the left becomes fixed and creates a better experience for the viewers of projects.

**Comment by ganigeorgiev** [comment] 2021-02-04 17:30
Hm, that actually I'm not sure how could be presented on a design image. Especially for desktop prototypes, where the design size is dynamic and the preview scrollbars depends on the user's available viewport.

@mvwijland Could you elaborate more on your request?

**Comment by mvwijland** [comment] 2021-02-05 10:10
You can set the top and the bottom to be fixed. That is a great option and helps user understand the prototype.
Most of the times the top is a menu. But, sometimes, the menu can be on the left. (Or you can have a panel on the right).

The prototype becomes more real for the users, when a left panel menu sticks to the screen.

See my attached image, a quick mock-up.

Would it be possible to fix a part of the left screen?

**Comment by ganigeorgiev** [comment] 2021-02-05 10:20
@mvwijland Thanks for the reply. Could you attach your mockup again? GitHub seems to ignore mail attachments.

**Comment by mvwijland** [comment] 2021-02-05 10:28
![FixedLeftMenu](https://user-images.githubusercontent.com/936091/107021929-0836b580-67a5-11eb-93fc-1dd75348ca40.png)

The image shows a menu and a topbar with some lorem ipsum content. The menu is fixed on the left side. The topbar/header is fixed on the top.

**Comment by ganigeorgiev** [comment] 2021-02-05 11:00
Thank you for the mockup. The problem with adding a fixed sidebar is that the preview screen doesn't have a fixed height. For example if designer select a 200x600px fixed side area and the user is previewing the screen on a larger viewport the end result may not look as intended. One solution could be to add support to specify background color only for a fixed area, but that I guess will work only when the fixed area has a solid background. Another option could be to require the user to export the design screen with "filled" remaining background top to bottom.

In my opinion this feature will clutter the UI additionally without adding too much value for the end user.
The level of prototype you are looking for is more suitable for complete design apps like Figma, XD or [Penpot](https://penpot.app/) (this project is also open source).

I'll close the issue, but if someone else disagree and/or think that it could be handled without too much hassle, please comment and I'll reopen it.

**Closed by ganigeorgiev** 2021-02-05 11:00 UTC
