### ISSUE TITLE
/var/www/html/vendor does not exist and could not be created.

### ISSUE THREAD

**Issue by senadaruc** [presentator/presentator#189] opened 2022-08-04 17:25 UTC
Trying to install at Ubuntu Docker getting this error!

`root@presentator:~/presentator# ./compose/scripts/setup
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 103 installs, 0 updates, 0 removals

In Filesystem.php line 268:
                                                                 
  /var/www/html/vendor does not exist and could not be created.  
                                                                 

install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]

Yii Application Initialization Tool v1.0

  Start initialization ...`

Any help please?

**Comment by ganigeorgiev** [comment] 2022-08-04 17:37
There are 2 docker setups :
- one that is used for development where each Presentator component (spa, api) is on its own
- and another one that is suitable for production and contains everything in a single distributed docker image - https://hub.docker.com/r/ganigeorgiev/presentator (https://github.com/presentator/presentator-docker)

From your error message, it seems that you are trying to setup the development environment. The error indicates probably a permission issue because usually `/var/www/...` is usually owned by the `www-data` user so make sure that it is added to your current user group and/or that you have permission to create/modify the `/var/www/html` directory.

If you are trying to install Presentator on production environment, then please follow either the [starter package instructions](https://github.com/presentator/presentator-starter) or its [dockerized version](https://github.com/presentator/presentator-docker) (also contains an [example with docker-compose](https://github.com/presentator/presentator-docker/tree/master/docker-compose-example)).

**Comment by senadaruc** [comment] 2022-08-04 18:15
Nice, I just puled the image, so now which config to use for the IMAGE?

**Comment by ganigeorgiev** [comment] 2022-08-04 18:38
Check the Quick start guide to see which file you'll need to mount as volume - https://github.com/presentator/presentator-docker#quick-start.

You could also check the docker-compose example - https://github.com/presentator/presentator-docker/tree/master/docker-compose-example for a demo usage of the docker image.

**Comment by senadaruc** [comment] 2022-08-04 19:34
Thanks, and after trying all possible install options, I give up :) In every single option, there is some problem that is hard to find a solution to. 

![Screenshot 2022-08-04 at 21 34 03](https://user-images.githubusercontent.com/14252382/182937604-c933443c-a185-4043-9313-899bd278df1a.png)

**Comment by ganigeorgiev** [comment] 2022-08-04 19:41
I'm sorry that you are experiencing issues with the installation (v3 will eliminate the need of any upfront setup).

The first error indicates that you don't have the php dom extension installed. You could find all requirements listed here - https://github.com/presentator/presentator-starter#requirements.

The seconds error is because you are trying to create a new composer project in a non-empty folder.

**Comment by senadaruc** [comment] 2022-08-04 19:42
On my local Docker, all works fine! But the same steps on Cloud-hosted Docker is not working...

**Comment by ganigeorgiev** [comment] 2022-08-04 19:47
Could you post what exactly steps have you taken? It's hard to help you debug the issue without full info on what commands have you executed.

**Comment by senadaruc** [comment] 2022-08-04 19:54
1st I tried the https://github.com/presentator/presentator at my local Docker on MacOsx, and all works fine.
The same steps at my Cloud Docker are not working!

2nd I tried the https://github.com/presentator/presentator-docker on my Cloud Docker, and it is not even booting since the setup is half finished, I have only the IMG where I tried to setup with docker-compose.yml, and nothing is happening; I receive just an empty web server.

3rd I tried to build without a Docker and had many errors even if I was using the Composer.

So three install options are failing in Cloud Docker on Ubuntu, where my local Docker 1st solution works.


Thanks,

**Comment by ganigeorgiev** [comment] 2022-08-04 20:05
As for the last option - what php extensions have you installed, did you verified the [requirements list](https://github.com/presentator/presentator-starter#requirements)? Can you post your `phpinfo` here?

I really want to help you, but you don't seem to follow exactly the available instructions and I don't know how to reproduce the issues you are experiencing without information of the commands that you've executed and the installation steps that you've taken.

**Comment by senadaruc** [comment] 2022-08-04 20:07
I just delete the Cloud VM because I gave up :) I have been trying to set up since last night without success. 

If you want I can send you the login so you can test yourself on my cloud VM ?

Thanks,

**Comment by ganigeorgiev** [comment] 2022-08-04 20:15
I'm sorry. Currently I don't have the time to install Presentator for you. I can help you to debug your issues, but you need to provide a little more information on what actually you are doing.

I'll close the issue for now, but if you still want to self-host Presentator, my advice will be:
1. If you are not familiar with Docker, use directly https://github.com/presentator/presentator-starter
2. Make sure that your php setup complies with the [minimum requirements](https://github.com/presentator/presentator-starter#requirements). Presentator currently supports PHP7.1-7.4 (8+ is not tested).
3. Follow exactly the starter package instructions - https://github.com/presentator/presentator-starter#installation.

**Closed by ganigeorgiev** 2022-08-04 20:15 UTC
