### ISSUE TITLE
Screen upload fails after 30 seconds

### ISSUE THREAD

**Issue by katalysis** [presentator/presentator#132] opened 2020-04-16 13:56 UTC
I can upload files to Presentator if the upload takes less than 30 seconds but anything taking more than that fails.

My PHP settings allow larger files and longer times - is there a setting in the app somewhere to control this?

**Comment by ganigeorgiev** [comment] 2020-04-16 14:13
Hm, execution times should be handled by the environment (php/server) configuration.

What are that the values of `max_input_time` and `max_execution_time`?

**Comment by katalysis** [comment] 2020-04-16 14:17
Both look good at 120 seconds: https://presentator.katalysis.net/info.php

I'm wondering about mysql wait_timeout but not sure how to investigate further.

**Comment by ganigeorgiev** [comment] 2020-04-16 14:36
The php config looks fine. My guess is that this is nginx/apache configuration.

Please check if there are any nginx directives that could limit the request processing time (`proxy_connect_timeout`, `proxy_send_timeout`, `proxy_read_timeout`, `fastcgi_send_timeout`, `fastcgi_read_timeout`, etc.).

**Comment by katalysis** [comment] 2020-04-16 15:01
Only one in default config was  keepalive_timeout  65;

Set some overrides for virtual host:

proxy_connect_timeout       600;
proxy_send_timeout          600;
send_timeout                600;
keepalive_timeout           600;
fastcgi_send_timeout        600;
fastcgi_read_timeout        600;

Uploads still error out on 30 seconds.

**Comment by ganigeorgiev** [comment] 2020-04-16 15:41
Since you are running nginx behind apache, could you check also the httpd/fastcgi settings (eg. `FcgidIdleTimeout`, `FcgidProcessLifeTime`, `FcgidConnectTimeout`, etc.)?

**Comment by katalysis** [comment] 2020-04-17 09:39
We've tweaked settings all over the server and nothing makes a difference.

I've just tried the same file on https://app.presentator.io and I get the same issue there too so the time out seems to be set the app and not the hosting?

My internet connection is only 16mbps so a retina screen image png will be 6-8mb which will fail to upload in the 30 seconds limit.

**Comment by ganigeorgiev** [comment] 2020-04-17 10:20
@katalysis The free service (aka. https://app.presentator.io) uses common default php/nginx timeout settings so that is expected to fail there (in additional the screen upload file size is also limited to around 5MB).

I'll try to reproduce it locally, but the application doesn't  have any `ini_set` calls, so I'm pretty sure this is a server configuration.

**Comment by ganigeorgiev** [comment] 2020-04-17 10:50
@katalysis I've just reproduced it locally and you were right - the upload request is actually canceled by the application, and more precisely at client side. Dropzone (the underlying js lib for file uploads) [has 30s default timeout setting for the XHR requests](https://www.dropzonejs.com/#config-timeout).

I will set it to 0, so that the timeouts are only handled by the server.

This will be fixed in the upcoming v2.5.0 release (planned for 20-21 Apr).

**Comment by katalysis** [comment] 2020-04-17 13:01
Thank you @ganigeorgiev I'll look out for the update.

**Comment by ganigeorgiev** [comment] 2020-04-20 13:57
@katalysis The issue should be fixed in the latest v2.5.0 release.

**Closed by ganigeorgiev** 2020-04-20 13:57 UTC
Labels: bug, support
