### ISSUE TITLE
Comments Notifications do not display in Chrome

### ISSUE THREAD

**Issue by TonyBarganski** [presentator/presentator#161] opened 2021-01-06 09:09 UTC
In Safari, I see comments in the notifications panel but cannot see them in Chrome Version 87.0.4280.88 (Official Build) (x86_64).

**Comment by ganigeorgiev** [comment] 2021-01-06 11:22
I'm with the same chrome version and I can not reproduce the issue. Both the notifications panel and the screen's comments panel work as expected.

Could you provide more details/screenshot? Can you reproduce it on the free service (aka. https://app.presentator.io)?

**Comment by TonyBarganski** [comment] 2021-01-06 22:03
@ganigeorgiev I don't see the issue on the free service at https://app/presentator.io, i.e. I see the notifications within the Notifications panel on both Chrome and Safari however, I don't see the Notifications in Chrome on our self-hosted server (version: 2.8.2 - same as the 'free service')

**Comment by ganigeorgiev** [comment] 2021-01-07 02:59
Hm, there shouldn't be any differences since the frontend is prebuilt. Are you sure that the comments are not marked as resolved/read? Are you an admin of the project?

**Comment by TonyBarganski** [comment] 2021-01-08 11:08
Comments are not marked as resolved or read.
I see the same user in both. I will test on another computer over the weekend.

**Comment by ganigeorgiev** [comment] 2021-01-08 16:06
@TonyBarganski I've just tested it with BrowserStack on multiple different platforms (including older versions of Chrome) and everything seems to work as expected. If you see the text "No notifications to show." then it shouldn't be a browser compatibility issue. If you are using Presentator as super user for your local setup, then my guess is that you are not assigned as admin to the project you are expecting notifications.

**Comment by TonyBarganski** [comment] 2021-01-09 21:21
I cannot tell what the issue was but now all "others" notifications are visible in the notifications panel. Strange. Closing this ticket.

**Comment by TonyBarganski** [comment] 2021-01-09 21:33
After further testing, I can confirm this is Not an issue in Chrome's *Incognito* mode but is in normal mode. There are no plugins running in normal mode so hard for me to see why this behaviour is occuring.

**Comment by ganigeorgiev** [comment] 2021-01-10 04:03
@TonyBarganski I'm still unable to reproduce it.
Do you have any js errors in the console (F12)?
Could you inspect the result of `api/screen-comments/unread` request when you open the notifications panel (the request could be checked in the Network dev tools tab)?

**Comment by TonyBarganski** [comment] 2021-01-10 05:48
<img width="938" alt="Presentator - screen comments - network calls" src="https://user-images.githubusercontent.com/46673133/104115380-f84fc100-531f-11eb-8204-d61e7ea91cb1.png">

<img width="957" alt="Presentator - screen comments - js calls" src="https://user-images.githubusercontent.com/46673133/104115439-86c44280-5320-11eb-939d-3a6a5e923523.png">

**Comment by ganigeorgiev** [comment] 2021-01-10 06:09
@TonyBarganski Hm, is it possible that Chrome has cached some previous misconfigured redirect rule? That would explain why you are not experiencing errors when you use the Incognito mode.
Could you try to go on the Network dev tools tab, click on the "Disable cache" checkbox and reload the page while the dev tools panel is opened?

**Comment by TonyBarganski** [comment] 2021-01-10 16:22
Yes, this worked! Disabling cache on the network tab of the dev tools. What is the permanent fix for this?

**Comment by ganigeorgiev** [comment] 2021-01-10 17:06
I'd say it is safe to leave it as it is. I guess that at some point while configuring your local setup one of your redirect/rewrite rule was incorrect and your browser most likely has cached that state. You could add cache control/expires headers in your server config if you want to make sure that your users doesn't have some broken cached state.

I'll close the issue, but if you are still experiencing any errors please comment.

**Closed by ganigeorgiev** 2021-01-10 17:06 UTC
Labels: to check
